import ChartPie from './pie.vue'
import ChartBar from './bar.vue'
import ChartScatter from './scatter.vue'
import Cbox from './cbox.vue'
import CboxOther from './cbox-other.vue'
import ChartMap from './map.vue'
import MapAffix from './map-affix.vue'
import CboxIndexes from './cbox-indexes.vue'
import CboxIndex from './cbox-index.vue'
import Tablex from './tablex.vue'
import TablexOrg from './tablex-org.vue'
export { ChartPie, ChartBar, CboxIndex, MapAffix, ChartScatter, Cbox, CboxOther, ChartMap, CboxIndexes, Tablex, TablexOrg }